"""Generates the firmware's font vocabulary from the renderer's own table
(docs/plans/fonts-and-icons.md Decision 3, B2): `firmware/epaper-schedule.yaml`'s
`font:` block and the `a.fonts[...]` lines inside the display lambda are
rewritten from `FONTS`/`FONT_ALIASES` rather than typed by hand, so the two
sides of the vocabulary cannot silently disagree about which spellings are
compiled. `display-mcp-cli firmware-fonts` (cli.py) is the entry point; this
module holds the logic so a test can call it directly.

**The fence mechanism.** Two regions of the YAML are owned by this
generator, each bounded by its own `start_marker`/`end_marker` pair --
one around the `font:` list (YAML `#` comments), one around the
`a.fonts[...]` lines inside the C++ lambda (`//` comments -- a `#` there
would be read by the C++ preprocessor as an invalid directive and fail to
compile, so the two fences can share a tag but not a comment leader).
`rewrite_fenced_region()` replaces exactly the text between one such pair
and is the function B4b reuses for a second tag (`image:` entries and
`a.icons[...]` lines) -- everything outside a fence, including the marker
lines themselves, is untouched byte for byte, and regenerating from the
same table twice produces the same bytes (idempotent).
"""

from __future__ import annotations

from .fonts import FAMILIES, FONT_ALIASES, FONTS, Face

# The fence markers this generator owns. Both pairs share the tag ("fonts")
# but not the comment leader: the YAML-level fence sits in ordinary YAML,
# the lambda-level fence sits inside a C++ string the display component
# compiles, where only `//` is a comment.
_GENERATED_BY = "generated by display-mcp-cli firmware-fonts, do not edit"
FONT_YAML_START = f"  # --- fonts: {_GENERATED_BY} ---"
FONT_YAML_END = "  # --- end fonts ---"
FONT_LAMBDA_START = f"      // --- fonts: {_GENERATED_BY} ---"
FONT_LAMBDA_END = "      // --- end fonts ---"


def rewrite_fenced_region(text: str, start_marker: str, end_marker: str, body: str) -> str:
    """Replace the text strictly between one `start_marker` .. `end_marker`
    pair with `body`, leaving the markers and everything outside them
    byte-for-byte untouched. `start_marker`/`end_marker` are matched
    verbatim (including whatever leading indentation the caller bakes into
    them), so the marker's own line keeps its indentation across a
    regeneration. Idempotent: calling this again with the same `body`
    reproduces exactly this output, since only the generated content
    between the (unmoved) markers changes.

    Raises `RuntimeError`, naming which marker and why, if the fence isn't
    intact: a marker missing entirely, a marker appearing more than once
    (which start/end pair would it be?), or the end marker appearing before
    the start.
    """
    for marker in (start_marker, end_marker):
        count = text.count(marker)
        if count == 0:
            raise RuntimeError(f"fence marker not found -- has it been renamed? {marker!r}")
        if count > 1:
            raise RuntimeError(
                f"fence marker appears {count} times, expected exactly 1: {marker!r}"
            )
    start = text.index(start_marker) + len(start_marker)
    end = text.index(end_marker)
    if end < start:
        raise RuntimeError(
            f"fence end marker {end_marker!r} appears before its start marker {start_marker!r}"
        )
    return text[:start] + "\n" + body.rstrip("\n") + "\n" + text[end:]


def _file_spec(face: Face) -> str:
    """The `file: { type: gfonts, ... }` mapping for one face's `font:`
    entry -- `italic: true` only when the style actually is italic, omitted
    (ESPHome's own default) otherwise, matching what the hand-written YAML
    did and what ESPHome 2026.8.2's `font` component accepts
    (`EXTERNAL_FONT_SCHEMA`'s `italic` defaults to `False`)."""
    typeface = FAMILIES[face.family].typeface
    parts = ["type: gfonts", f"family: {typeface}", f"weight: {face.weight}"]
    if face.italic:
        parts.append("italic: true")
    return "{ " + ", ".join(parts) + " }"


def render_font_block(fonts: dict[str, Face] = FONTS) -> str:
    """The generated body of the `font:` fence: one entry per canonical
    face in `fonts`, in the table's own order (family, then style, then
    `SIZES`) -- `id` from `Face.yaml_id`, `size`, and `glyphsets:
    [GF_Latin_Core]` for every face, plus `mono`'s `glyphs:` string (every
    code point in its `extra_glyphs`, exactly as `Face.extra_glyphs`
    states it -- not copied from the old YAML) so every mono size, not
    just one, compiles the box-drawing and block glyphs."""
    lines: list[str] = []
    for face in fonts.values():
        lines.append(f"  - file: {_file_spec(face)}")
        lines.append(f"    id: {face.yaml_id}")
        lines.append(f"    size: {face.size}")
        lines.append("    glyphsets: [GF_Latin_Core]")
        if face.extra_glyphs:
            codepoints = sorted({cp for r in face.extra_glyphs for cp in r})
            glyphs = "".join(chr(cp) for cp in codepoints)
            lines.append(f'    glyphs: "{glyphs}"')
    return "\n".join(lines)


def render_fonts_lines(
    fonts: dict[str, Face] = FONTS, aliases: dict[str, str] = FONT_ALIASES
) -> str:
    """The generated body of the lambda's `a.fonts[...]` fence: one line per
    canonical name in `fonts` pointing at its own id, then one line per
    alias in `aliases` pointing at the same id its target resolves to --
    so every spelling `resolve_font()` accepts, the firmware accepts too."""
    lines: list[str] = []
    for name, face in fonts.items():
        lines.append(f'      a.fonts["{name}"] = id({face.yaml_id});')
    for alias, target in aliases.items():
        lines.append(f'      a.fonts["{alias}"] = id({fonts[target].yaml_id});')
    return "\n".join(lines)


def generate_firmware_yaml(text: str) -> str:
    """The whole rewrite: both fences, regenerated from `FONTS`/
    `FONT_ALIASES`. Everything outside the two fenced regions -- the
    header comment, the icons, the rest of the file -- is untouched."""
    text = rewrite_fenced_region(text, FONT_YAML_START, FONT_YAML_END, render_font_block())
    text = rewrite_fenced_region(text, FONT_LAMBDA_START, FONT_LAMBDA_END, render_fonts_lines())
    return text
