"""Generates the firmware's font and icon vocabulary from the renderer's own
tables (docs/plans/fonts-and-icons.md Decision 3/4, B2/B4b):
`firmware/epaper-schedule.yaml`'s `font:`/`image:` blocks and the
`a.fonts[...]`/`a.icons[...]` lines inside the display lambda are rewritten
from `FONTS`/`FONT_ALIASES` and `ICONS`/`ICON_SIZES` rather than typed by
hand, so the two sides of the vocabulary cannot silently disagree about
which spellings are compiled. `display-mcp-cli firmware-vocabulary`
(cli.py; `firmware-fonts` is kept as an alias) is the entry point; this
module holds the logic so a test can call it directly.

**The fence mechanism.** Four regions of the YAML are owned by this
generator, each bounded by its own `start_marker`/`end_marker` pair -- one
each around the `font:`/`image:` lists (YAML `#` comments), one each around
the `a.fonts[...]`/`a.icons[...]` lines inside the C++ lambda (`//`
comments -- a `#` there would be read by the C++ preprocessor as an invalid
directive and fail to compile, so a YAML-level and a lambda-level fence
share a tag but never a comment leader). `rewrite_fenced_region()` replaces
exactly the text between one such pair -- everything outside a fence,
including the marker lines themselves, is untouched byte for byte, and
regenerating from the same tables twice produces the same bytes
(idempotent).

**Icons, normalised on the firmware side, not aliased (B4b).** Every icon
now compiles at all five font slots (Decision 4), so `render_icons_lines()`
below emits exactly the 95 canonical `name/slot` keys -- no px-spelling
aliases, unlike fonts. `render_fonts_lines()` itself now emits only the 110
canonical font keys plus the five bare legacy names (`xl lg md sm xs`),
dropping the 50 px-spelling aliases `FONT_ALIASES` also holds: a document
that writes `petrona/36` reaches the firmware's `assets.fonts["petrona/md"]`
entry via `display_list.h`'s own `normalize_font_key()`, which maps the
size half of a spelling from its pixel count to its slot before either map
is consulted. That halves the `std::map` this generator makes the firmware
rebuild on every wake (the B2 review's own heap note) without changing
what the renderer accepts -- `FONT_ALIASES` itself is untouched, since the
renderer still resolves every spelling directly.
"""

from __future__ import annotations

from . import ICON_SIZES, ICONS
from .fonts import FAMILIES, FONT_ALIASES, FONTS, SLOTS, Face

# The fence markers this generator owns. All four pairs share one tag but
# not the comment leader: a YAML-level fence sits in ordinary YAML, a
# lambda-level fence sits inside a C++ string the display component
# compiles. The tag text itself still says "firmware-fonts" -- the
# subcommand's name through B4b -- rather than its current primary name
# "firmware-vocabulary": changing it would mean editing the four marker
# lines already committed in epaper-schedule.yaml (rewrite_fenced_region()
# matches them verbatim), for no behavioural gain, since `firmware-fonts`
# is kept as a working alias specifically so old muscle memory (and this
# text) keeps meaning the same command.
_GENERATED_BY = "generated by display-mcp-cli firmware-fonts, do not edit"
FONT_YAML_START = f"  # --- fonts: {_GENERATED_BY} ---"
FONT_YAML_END = "  # --- end fonts ---"
FONT_LAMBDA_START = f"      // --- fonts: {_GENERATED_BY} ---"
FONT_LAMBDA_END = "      // --- end fonts ---"
ICON_YAML_START = f"  # --- icons: {_GENERATED_BY} ---"
ICON_YAML_END = "  # --- end icons ---"
ICON_LAMBDA_START = f"      // --- icons: {_GENERATED_BY} ---"
ICON_LAMBDA_END = "      // --- end icons ---"

# The eleven MDI icons' `mdi:` slug, where it differs from the icon's own
# canonical name -- read off the hand-written YAML before this generator
# replaced it (`clock` -> `mdi:clock-outline` is the one rename; every other
# MDI icon's slug is just its own name). Every `ICONS` name *not* in this
# table is one of the eight lucide activity icons instead, and gets its
# `image:` entry from the committed PNG under `src/display_mcp/render/icons/`
# rather than from an `mdi:` slug (docs/plans/fonts-and-icons.md Decision 4).
_MDI_SLUGS: dict[str, str] = {
    "weather-sunny": "weather-sunny",
    "weather-partly-cloudy": "weather-partly-cloudy",
    "weather-cloudy": "weather-cloudy",
    "weather-rainy": "weather-rainy",
    "weather-snowy": "weather-snowy",
    "weather-night": "weather-night",
    "check": "check",
    "map-marker": "map-marker",
    "clock": "clock-outline",
    "alert": "alert",
    "battery": "battery",
}

# Relative to firmware/, where epaper-schedule.yaml lives -- confirmed to
# resolve under `esphome config` (B4b).
_ICON_PNG_DIR = "../src/display_mcp/render/icons"


def rewrite_fenced_region(text: str, start_marker: str, end_marker: str, body: str) -> str:
    """Replace the text strictly between one `start_marker` .. `end_marker`
    pair with `body`, leaving the markers and everything outside them
    byte-for-byte untouched. `start_marker`/`end_marker` are matched
    verbatim (including whatever leading indentation the caller bakes into
    them), so the marker's own line keeps its indentation across a
    regeneration. Idempotent: calling this again with the same `body`
    reproduces exactly this output, since only the generated content
    between the (unmoved) markers changes.

    Raises `RuntimeError`, naming which marker and why, if the fence isn't
    intact: a marker missing entirely, a marker appearing more than once
    (which start/end pair would it be?), or the end marker appearing before
    the start.
    """
    for marker in (start_marker, end_marker):
        count = text.count(marker)
        if count == 0:
            raise RuntimeError(f"fence marker not found -- has it been renamed? {marker!r}")
        if count > 1:
            raise RuntimeError(
                f"fence marker appears {count} times, expected exactly 1: {marker!r}"
            )
    start = text.index(start_marker) + len(start_marker)
    end = text.index(end_marker)
    if end < start:
        raise RuntimeError(
            f"fence end marker {end_marker!r} appears before its start marker {start_marker!r}"
        )
    return text[:start] + "\n" + body.rstrip("\n") + "\n" + text[end:]


def _file_spec(face: Face) -> str:
    """The `file: { type: gfonts, ... }` mapping for one face's `font:`
    entry -- `italic: true` only when the style actually is italic, omitted
    (ESPHome's own default) otherwise, matching what the hand-written YAML
    did and what ESPHome 2026.8.2's `font` component accepts
    (`EXTERNAL_FONT_SCHEMA`'s `italic` defaults to `False`)."""
    typeface = FAMILIES[face.family].typeface
    parts = ["type: gfonts", f"family: {typeface}", f"weight: {face.weight}"]
    if face.italic:
        parts.append("italic: true")
    return "{ " + ", ".join(parts) + " }"


def render_font_block(fonts: dict[str, Face] = FONTS) -> str:
    """The generated body of the `font:` fence: one entry per canonical
    face in `fonts`, in the table's own order (family, then style, then
    `SIZES`) -- `id` from `Face.yaml_id`, `size`, and `glyphsets:
    [GF_Latin_Core]` for every face, plus `mono`'s `glyphs:` string (every
    code point in its `extra_glyphs`, exactly as `Face.extra_glyphs`
    states it -- not copied from the old YAML) so every mono size, not
    just one, compiles the box-drawing and block glyphs."""
    lines: list[str] = []
    for face in fonts.values():
        lines.append(f"  - file: {_file_spec(face)}")
        lines.append(f"    id: {face.yaml_id}")
        lines.append(f"    size: {face.size}")
        lines.append("    glyphsets: [GF_Latin_Core]")
        if face.extra_glyphs:
            codepoints = sorted({cp for r in face.extra_glyphs for cp in r})
            glyphs = "".join(chr(cp) for cp in codepoints)
            lines.append(f'    glyphs: "{glyphs}"')
    return "\n".join(lines)


def render_fonts_lines(
    fonts: dict[str, Face] = FONTS, aliases: dict[str, str] = FONT_ALIASES
) -> str:
    """The generated body of the lambda's `a.fonts[...]` fence: one line per
    canonical name in `fonts` pointing at its own id, then one line per
    *bare* alias in `aliases` (the five legacy names with no `/` --
    `xl lg md sm xs`) pointing at the same id its target resolves to.

    The other fifty entries `aliases` holds -- a face's own pixel-count
    spelling, e.g. `"petrona/36"` for `"petrona/md"` -- are deliberately
    left out here (B4b): `display_list.h`'s `normalize_font_key()`
    normalises the size half of a spelling from its pixel count to its slot
    before either vocabulary map is consulted, so `"petrona/36"` reaches
    `assets.fonts["petrona/md"]` without needing its own map entry. A bare
    name has no size half to normalise (`normalize_font_key()` leaves a
    name with no `/` alone), so those five still need their own line."""
    lines: list[str] = []
    for name, face in fonts.items():
        lines.append(f'      a.fonts["{name}"] = id({face.yaml_id});')
    for alias, target in aliases.items():
        if "/" not in alias:
            lines.append(f'      a.fonts["{alias}"] = id({fonts[target].yaml_id});')
    return "\n".join(lines)


def _icon_yaml_id(name: str, slot: str) -> str:
    """The firmware `image:` entry id for one icon/slot, deterministic from
    the pair (`"school-day", "md"` -> `"ic_school_day_md"`) -- matches the
    hand-written ids' own shape (`ic_check_sm`, `ic_weather_sunny_lg`, ...)."""
    return "ic_" + name.replace("-", "_") + "_" + slot


def render_icon_block(icons: dict[str, frozenset[str]] = ICONS) -> str:
    """The generated body of the `image:` fence: one entry per `name/slot`
    (docs/plans/fonts-and-icons.md Decision 4) -- an MDI icon (`_MDI_SLUGS`)
    gets `file: mdi:<slug>` and `resize: <px>x<px>`, the way every icon did
    before B4b; a lucide activity icon gets its own committed PNG under
    `_ICON_PNG_DIR` instead, with no `resize:` (the file is already exactly
    `px` by `px`). Iterates slots in `SLOTS`' own order (`xs sm md lg xl`)
    within each name, matching the font block's own size-then-name order."""
    lines: list[str] = []
    for name, slots in icons.items():
        for slot in SLOTS:
            if slot not in slots:
                continue
            px = ICON_SIZES[slot]
            id_ = _icon_yaml_id(name, slot)
            if name in _MDI_SLUGS:
                lines.append(
                    f"  - {{ file: mdi:{_MDI_SLUGS[name]}, id: {id_}, type: BINARY, "
                    f"transparency: chroma_key, resize: {px}x{px} }}"
                )
            else:
                lines.append(
                    f"  - {{ file: {_ICON_PNG_DIR}/{name}-{px}.png, id: {id_}, "
                    "type: BINARY, transparency: chroma_key }"
                )
    return "\n".join(lines)


def render_icons_lines(icons: dict[str, frozenset[str]] = ICONS) -> str:
    """The generated body of the lambda's `a.icons[...]` fence: one line per
    `name/slot`, the canonical spelling only -- unlike fonts, an icon has no
    bare legacy alias and (Decision 4) no px-spelling alias either, since
    `display_list.h`'s `normalize_size_alias()` handles a pixel-count `z`
    the same way it handles a pixel-count font size."""
    lines: list[str] = []
    for name, slots in icons.items():
        for slot in SLOTS:
            if slot not in slots:
                continue
            lines.append(f'      a.icons["{name}/{slot}"] = id({_icon_yaml_id(name, slot)});')
    return "\n".join(lines)


def generate_firmware_yaml(text: str) -> str:
    """The whole rewrite: all four fences, regenerated from `FONTS`/
    `FONT_ALIASES` and `ICONS`/`ICON_SIZES`. Everything outside the fenced
    regions -- the header comments, the rest of the file -- is untouched."""
    text = rewrite_fenced_region(text, FONT_YAML_START, FONT_YAML_END, render_font_block())
    text = rewrite_fenced_region(text, FONT_LAMBDA_START, FONT_LAMBDA_END, render_fonts_lines())
    text = rewrite_fenced_region(text, ICON_YAML_START, ICON_YAML_END, render_icon_block())
    text = rewrite_fenced_region(text, ICON_LAMBDA_START, ICON_LAMBDA_END, render_icons_lines())
    return text
